name: aist_cargo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Utils
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  go_router: ^14.3.0
  flutter_screenutil:
    ^5.9.3

    # -- localization -- #
  flutter_localizations:
    sdk: flutter
  slang: ^3.32.0
  slang_flutter: ^3.32.0

  # -- ui -- #
  auto_size_text: ^3.0.0
  pin_code_fields: ^8.0.1

  # -- image -- #
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  image_picker: ^1.0.0

  # -- codegen -- #
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # -- networking -- #
  dio: ^5.7.0

  # -- state management -- #
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^8.0.3
  dartz: ^0.10.1

  # -- logging -- #
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # -- utils -- #
  flutter_gen_runner: ^5.8.0

  # -- codegen -- #
  build_runner: ^2.4.13
  slang_build_runner: ^3.32.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
